sudo: false

language: go

git:
  depth: 1

install: 
  - go get github.com/gohugoio/hugo

script:
  - git submodule init
  - git submodule update
  - rm -rf public
  - mkdir public
  - git worktree prune
  - rm -rf .git/worktrees/public/
  - git branch gh-pages
  - git worktree add -B gh-pages public ../gh-pages
  - rm -rf public/*
  - hugo
  - cd public/
  - cp ../CNAME .
  - git add --all
  - git commit -m "add message"
  - git push origin gh-pages:gh-pages

  # Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master