sudo: false

language: go

git:
  depth: 1

install: 
  - go get github.com/gohugoio/hugo

before_script:
  - git submodule init
  - git submodule update
  - git checkout --orphan gh-pages
  - git reset --hard
  - git commit --allow-empty -m "Initializing gh-pages branch"
  - git push upstream gh-pages
  - git checkout master

script:
  - rm -rf public
  - git worktree add -B gh-pages public origin/gh-pages
  - hugo
  - cd public
  - cp ../CNAME .
  - git add --all
  - git commit -m "Publishing to gh-pages" 
  - cd ..
  - git push origin gh-pages

  # Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master