baseURL = "https://2017yfb1001800.cn/"
languageCode = "zh-cn"
title = "可持续演化的智能化软件理论、方法和技术"
theme = "simplicity-master"

defaultContentLanguage = "en"
disqusShortname = "test"
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""
pygmentsCodeFences = true
pygmentsStyle = "native"
pygmentsUseClasses =  true
[author]
  homepageText = "可持续演化的智能化软件理论、方法和技术"
  name = "可持续演化的智能化软件理论、方法和技术项目组"
[imaging]
  anchor = "smart"
  resampleFilter = "box"
  quality = 75
[[menu.pages]]
  name = "Projects"
  weight = -100
  identifier = "projects"
  url = "/projects/"
[[menu.pages]]
  name = "Photos"
  weight = -90
  identifier = "photos"
  url = "/photos/"
[outputs]
  home = ["HTML"]
  page = ["HTML"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  taxonomyTerm = ["HTML"]
[params]
  adsenseClient = ''
  adsenseSlot = ''
  description = "A blog about everything."
  displayPostLanguage = true
[permalinks]
  posts = "/:year/:month/:day/:slug/"
[pygmentsOptions]
  linenos = false
